BOARD_TAG = pro
BOARD_SUB = 8MHzatmega328
ARDUINO_PORT = /dev/ttyAMA0
ARDUINO_LIBS = EEPROM TimerOne
ARDUINO_SKETCHBOOK = ./

MONITOR_BAUDRATE = 38400
AVRDUDE_ARD_BAUDRATE = 38400
include $(ARDMK_DIR)/Arduino.mk
